# -*- coding: utf-8 -*-
"""Assignment- Password Reminder

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rAumVD1RGjqM6YLCnGQIQe9yMJ4PCsyA
"""

password = "goodworld"
user = "Salih"
enter_user = input("Please Enter User Name: ").title()
if user == enter_user :
  print("Hello {}! Your pasword = {}".format(user, password))
else:
  print("Hello {}! See you later".format(enter_user))

