# -*- coding: utf-8 -*-
"""Assignment/2 (Profit Calculation)13.04

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zmO5oWXiUO0lwa-0xmfwvuusCUqvd9EJ
"""

# Your boss wants you to prepare the payrolls of the workers in your department.
# You have to convert the amount of dollars into payroll format.
# In order to help move things along, you have volunteered to write a code that
# will take a float and return the money in the following format

ali_maas= 3
recep_maas= 29.99
salih_maas =4.1

liste_maas = "ali'nin maası $%.2f recebin maası $%.2f salihin maası $%.2f" % (ali_maas,recep_maas,salih_maas)
print(liste_maas)

