# -*- coding: utf-8 -*-
"""Assignment-008/2 (Profit Calculation)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zmO5oWXiUO0lwa-0xmfwvuusCUqvd9EJ
"""

# After finishing the tasks correctly, then submit your answers (codes) as plain text which shows you did correctly.
# Leave two empty lines between your answers (regarding two tasks).
# Task - 1 :
# You work for a manufacturer as a programmer and have been asked to calculate the total profit made on the sales of a product.
# You are given a dictionary (sales) containing the cost price per unit (in dollars),
# sell price per unit (in dollars),and the beginning inventory. 
# Write a program to return the total profit made, rounded to the nearest dollar. Assume all of the inventory has been sold.
# The name and the keys of the dictionary are constant, so use them as they are.


sales = {
  "cost_value": 31.87,
  "sell_value": 45.00,
  "inventory": 1000
} 

total_profit= (float(sales["sell_value"]) - float(sales["cost_value"])) * float(sales["inventory"])
print(round(total_profit))
