# -*- coding: utf-8 -*-
"""Assignment-008/1 (The Most Frequent Element)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zmO5oWXiUO0lwa-0xmfwvuusCUqvd9EJ
"""

#After finishing the task correctly, then submit your answer (code) as plain text which shows you did correctly.
#Task : Find out the most frequent number and its frequency.

#Write a program that;

#Finds out the most frequent number in the given list.
#Calculates its frequency.
#Prints out the result such as :

numbers = [1, 3, 7, 4, 3, 0, 3, 6, 3]
tekrar_cok = max(numbers, key = numbers.count)
tekrar_kac = numbers.count(tekrar_cok)
print("the most frequent number is {} and it was {} times repeated".format(tekrar_cok,tekrar_kac))

