# -*- coding: utf-8 -*-
"""fibonacci

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mvtsuwnC4OB0EGGNkxACz9bAYbcbqpG9
"""

fibo = []
x, y = 0, 1
while x<55:
  x,y = y, x+y
  fibo.append(x)
print(fibo)

