# -*- coding: utf-8 -*-
"""FizzBuzz

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gq2cDU7llSMlso3muNdYOh96qiRy6t56
"""

for i in range(1,101):
  if not i%3 and i%5 != 0 :
    print("Fizz")
  elif i%5 == 0 and i%3 != 0 :
    print("Buzz")
  elif i%15 == 0:
    print("FizzBuzz")
  else:
    print(i)